<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-10-19 00:29

from django.conf import settings
=======
# Generated by Django 3.2.8 on 2021-10-18 04:24

>>>>>>> fdb1a7bf510986878a22a39d23404433d2e59c6d
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> fdb1a7bf510986878a22a39d23404433d2e59c6d
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
>>>>>>> fdb1a7bf510986878a22a39d23404433d2e59c6d
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> fdb1a7bf510986878a22a39d23404433d2e59c6d
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
